apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.image.name }}
    namespace: {{ .Values.image.namespace }}
    labels:
        app: {{ .Values.image.name }}
spec:
    ports:
      - port: {{ .Values.image.port }}
        protocol: TCP
        targetPort: {{ .Values.image.port }}
    selector:
        app: {{ .Values.image.name }}
    type: NodePort # LoadBalancer for Azure
