################################
### Deployment
################################

# Security Context
deploymentSecurityContextEnabled: false   # later change to true for user to use

appName: gas-storage-optim
namespace: czpfm-prod

replicas: 1

#image: "mcr.microsoft.com/dotnet/samples:aspnetapp"
image: "datqpczpfmacr01.azurecr.io/gas-stor-opt:20240131.1"
containerPort: 8080
secretMountPath: "/mnt/secrets-store"


# Deployment Resources  --> request section is required to use KEDA-CPU/MEMORY
deploymentResourcesEnabled: true
memoryRequest: "256Mi"
cpuRequest: "500m"
memoryLimit: "2048Mi"

deploymentCpuLimitEnable: false
cpuLimit: "100m"


################################
### Secret Provider Class
################################

secretProviderClassEnabled: false
userAssignedIdentityID: "741c74ad-90a2-4f18-a8f4-9d79195a9695"
keyvaultName:  dat-q-akv-aks
tenantId: "36630e33-ef9b-4ed1-a948-6f85770a5636"

secretProviderObjects:
  - |
    objectName: CZPFM-gas-storage-optim-CLIENT-ID      # Use find & Replace to rename
    objectType: secret               # object types: secret, key, or cert
  - |
    objectName: CZPFM-gas-storage-optim-TENANT-ID      # Use find & Replace to rename
    objectType: secret               # object types: secret, key, or cert
  - |
    objectName: CZPFM-gas-storage-optim-CLIENT-SECRET      # Use find & Replace to rename
    objectType: secret               # object types: secret, key, or cert
  - |
    objectName: CZPFM-gas-storage-optim-ALLOWED-IDS      # Use find & Replace to rename
    objectType: secret               # object types: secret, key, or cert
  - |
    objectName: CZPFM-gas-storage-optim-LOGIN-REDIRECT-BASE-URL      # Use find & Replace to rename
    objectType: secret               # object types: secret, key, or cert
  - |
    objectName: CZPFM-gas-storage-optim-LOGOUT-REDIRECT-BASE-URL      # Use find & Replace to rename
    objectType: secret               # object types: secret, key, or cert


secretEnabled: false
secretObjects:
 - key: CLIENT_ID             # A key name inside the new secret - Use find & Replace to rename
   objectName: CZPFM-gas-storage-optim-CLIENT-ID      # Secret value to use
 - key: clientsecret
   objectName: key-vault-secret-2


secretAsEnv:
- name:
  key:
# - name: 
#   key: 

# Renamed variables from config map
AzureAppConfigurationManualEnabled: false    # don't know? don't change!
reconfiguredEnv:
- name: AzureAdClientId
  key: AzureAd__ClientId



################################
### Service
################################

servicePort: 80


################################
### Ingress
################################

ingressEnabled: true
ingressClass: azure-application-gateway
ingressHost: "dev.emdp.eon.com"
ingressPath: /czpfm-gas-storage-optim
ingressPathType: Prefix

ingressAnnotations:
  appgw.ingress.kubernetes.io/backend-path-prefix: "/"
  appgw.ingress.kubernetes.io/appgw-ssl-certificate: "emdp.eon.com"
  appgw.ingress.kubernetes.io/ssl-redirect: "true" 
  # appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
  # appgw.ingress.kubernetes.io/cookie-based-affinity-distinct-name: "true"
  # appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399, 404"
  # appgw.ingress.kubernetes.io/request-timeout: "20"